### ISSUE TITLE
cmake script should detect if gtest is already built

### ISSUE THREAD

**Issue by catageek** [trillek-team/trillek-vcomputer-module#25]
gtest target may be already built when vcomputer, used as a submodule, is built. Building twice gtest target results in an error.

CMakelist.txt should include the detection of gtest target in parent CMakeList.txt and not try to build it.

**Comment by catageek** [comment]
The more simple would be to use FindGTEST module instead of trying to build it internally.

**Comment by Zardoz89** [comment]
Yep, but findGTEST looks that not works on Ubuntu. I have GTest installed from ubuntu repos, and findGTest can't find it.

```
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
```

 I'm going to change to try it with findGtest, and if it fails, then try the enviroment variable...

**Comment by Zardoz89** [comment]
Check it now. Now try to find with findGTest (and I found that if GTest is compiled before by other project, it works), and if it fails, then try the environment variable way.

**Comment by catageek** [comment]
Fixed.
