### ISSUE TITLE
move vm to trillek repo?

### ISSUE THREAD

**Issue by ShaneD53** [trillek-team/trillek-vcomputer-module#3]
Since this is a part of Trillek it may be time to move the vm to Trillek? I'll create a repo for it and make you an owner.

**Comment by Zardoz89** [comment]
Sounds logic, but I can transfer the ownership of this repo to "trillke-team". So is not necessary creating a new repo to move the VM.

http://www.codelord.net/2012/03/31/migrating-to-a-github-organization/
