### ISSUE TITLE
Build issues on OS X

### ISSUE THREAD

**Issue by theshadow** [trillek-team/trillek-vcomputer-module#53]
I've tried a couple of things, other targets appear to build but this one refuses.

``` shell
[ 88%] Building CXX object tools/CMakeFiles/tda_view.dir/tda_view.cpp.o
In file included from /Users/xanderguzman/Projects/trillek-vcomputer-module/tools/tda_view.cpp:5:
In file included from /Users/xanderguzman/Projects/trillek-vcomputer-module/tools/include/os.hpp:12:
In file included from /Users/xanderguzman/Projects/trillek-vcomputer-module/build/config_main.hpp:20:
/usr/local/include/GLFW/glfw3native.h:125:1: error: unknown type name 'GLFWAPI'
GLFWAPI id glfwGetCocoaWindow(GLFWwindow* window);
^
/usr/local/include/GLFW/glfw3native.h:125:11: error: expected ';' after top level declarator
GLFWAPI id glfwGetCocoaWindow(GLFWwindow* window);
          ^
/usr/local/include/GLFW/glfw3native.h:133:1: error: unknown type name 'GLFWAPI'
GLFWAPI id glfwGetNSGLContext(GLFWwindow* window);
^
/usr/local/include/GLFW/glfw3native.h:133:11: error: expected ';' after top level declarator
GLFWAPI id glfwGetNSGLContext(GLFWwindow* window);
          ^
In file included from /Users/xanderguzman/Projects/trillek-vcomputer-module/tools/tda_view.cpp:5:
/Users/xanderguzman/Projects/trillek-vcomputer-module/tools/include/os.hpp:70:34: error: use of undeclared identifier 'glfwGetCocoaWindow'
                id cocoaWindow = glfwGetCocoaWindow(this->window);
                                 ^
/Users/xanderguzman/Projects/trillek-vcomputer-module/tools/tda_view.cpp:246:19: error: use of undeclared identifier 'GL_MAJOR_VERSION'
    glGetIntegerv(GL_MAJOR_VERSION, &OpenGLVersion[0]);
                  ^
/Users/xanderguzman/Projects/trillek-vcomputer-module/tools/tda_view.cpp:247:19: error: use of undeclared identifier 'GL_MINOR_VERSION'
    glGetIntegerv(GL_MINOR_VERSION, &OpenGLVersion[1]);
                  ^
7 errors generated.
make[2]: *** [tools/CMakeFiles/tda_view.dir/tda_view.cpp.o] Error 1
make[1]: *** [tools/CMakeFiles/tda_view.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by Zardoz89** [comment]
Could you say with that branch and commit, do you try it ? 

I don't have a OSX machine to test it, and these code, was borrow from an older version of Sigma. I need to take a look how is doing this now trillek-client-core

**Comment by theshadow** [comment]
<pre>
commit d0eb49b96c3d2512f0e896380ad9e2fbef8b119d
Author: Luis <luis.panadero@gmail.com>
Date:   Mon Feb 9 20:25:42 2015 +0100
    Update README with build instructions for windows [ci skip]
</pre>

**Comment by Zardoz89** [comment]
Ok. I'm asking to someone with OSX on IRC .... 

```
4:55 PM <zardoz84> Could some one take a look to this ? https://github.com/trillek-team/trillek-vcomputer-module/issues/53
5:07 PM <adam4813> Might be an outdated glfw?
5:07 PM <paultech> I do
5:07 PM <adam4813> paultech: and I think Meisaka have access to osx
5:08 PM ⇐ UplinkCoder quit (~ucoder@p54A34937.dip0.t-ipconnect.de) Ping timeout: 245 seconds
5:09 PM <paultech> That type is in glfw.h
5:10 PM <paultech> If you are loading glfw3native.h you must have the windows API and creation API ready
5:11 PM <paultech> On mac you need GLFW_EXPOSE_NATIVE_NSGL GLFW_EXPOSE_NATIVE_COCOA and linked to the coco framework
5:14 PM <paultech> I'd build but it requires gtest
5:15 PM <paultech> Confirmed I have same build problem on osx
5:16 PM <zardoz84> Ummm
5:19 PM <paultech> Better when I include glfw.h
5:19 PM <paultech> (since you are not suppose to just include natives)
5:21 PM <paultech> Also the wrong opengl headers
5:21 PM <paultech> You also do a few things weird
5:21 PM <paultech> void initGL(OS::OS& os) {
5:21 PM <paultech> You use a modern method to get version (GL_MAJOR_VERSION) before you check the context version
New messages
5:22 PM <zardoz84> I think that I should clean a bit more these code.... 
```

I would try to fix it today.

**Comment by theshadow** [comment]
Sounds great! Thanks!

**Comment by Zardoz89** [comment]
Thanks to Paultech, I managed to get it compiling and generating an valid executable, but looks that it's something wrong on the opengl code. Shows a gray window.
Try with this : https://github.com/Zardoz89/trillek-vcomputer-module/tree/fix_osx

**Comment by Zardoz89** [comment]
I think that I found the source of the problem ... OpenGL is core profile and I'm using some old stuff there : http://stackoverflow.com/questions/26378289/osx-opengl-4-1-glenablevertexattribarray-gldrawarrays-gl-invalid-operation

**Comment by Zardoz89** [comment]
Could do you check https://github.com/Zardoz89/trillek-vcomputer-module/tree/fix_osx
I think that now should work on OSX

**Comment by Zardoz89** [comment]
Builds, but I couldn't fix the problem with grey OpenGL windows. I opened an issue a bout it. Closing this.

**Comment by harshaxnim** [comment]
I have the same problem in mine. It'd be of great help if you tell me how you handled the "use of undeclared identifier 'GL_..." error? Thanks 😄

**Comment by milesrout** [comment]
@harshaxnim Can you please post the error message you got?

**Comment by harshaxnim** [comment]
I'm sorry I did not make it clear. I have the same problem in a separate program that I'm writing. I do not want to bother you so much if you're busy, but if can find time for me, this is the problem that I'm facing:
`error: use of undeclared identifier 'GL_MAJOR_VERSION'`
`error: use of undeclared identifier 'GL_MINOR_VERSION'`

I'm using SDL2, OpenGL 4.1 on Mac OS X 10.11.

If you could just tell me how you fixed it, the experience might help me to fix my problem too.

-H

P.S.: I guess you can close the issue :)
