### ISSUE TITLE
Skipping a 8-byte instruction should take 1 extra-cycle

### ISSUE THREAD

**Issue by catageek** [trillek-team/trillek-vcomputer-module#56]
IFEQ    %r1,0                            ; condition is false
IFEQ    %r1,0xBEBACAFE         ; skip this, should take 2 cycles to skip

The current implementation takes only 1 cycle for the second instruction.
The specification is not clear, but the extra cycle sounds logic.

**Comment by Zardoz89** [comment]
I agree, that we need to make more clear these point. But the CPU could check if the instruction have a long literral reading the first 4 byte (bits M and L are 1) and then do a pc=pc+8 instead of a pc=pc+4
